export const HEALTH_SUMMARY_LABELS: Record<string, string> = {
  generation_runs: "生成次数",
  degraded_runs: "降级生成次数",
  blocked_or_failed_runs: "阻断或失败次数",
  auto_repairs: "自动修复次数",
  trace_count: "生成轨迹数量",
  progression_count: "状态演进候选数",
  experience_quality_report_count: "体验质量报告数",
  quality_memory_pattern_count: "质量记忆模式数",
};

export const DISPLAY_VALUE_LABELS: Record<string, string> = {
  off: "关闭",
  shadow: "影子检查",
  report: "报告模式",
  assist: "辅助模式",
  enforce: "强制模式",
  metadata: "元数据记录",
  full: "完整记录",
  full_debug_when_failed: "失败时完整调试",
  read: "只读",
  candidate: "候选",
  active: "生效",
  legacy: "兼容模式",
  quick: "快速模式",
  standard: "标准模式",
  deep: "深度模式",
  local_patch: "局部修订",
  scene_rewrite: "整场重写",
  completed: "已完成",
  disabled: "已关闭",
  unavailable: "不可用",
  ok: "正常",
  fail: "未通过",
  green: "低风险",
  yellow: "中风险",
  red: "高风险",
  high: "高",
  medium: "中",
  low: "低",
  draft: "草稿",
  reviewed: "已评审",
  applied: "已应用",
  skipped: "已跳过",
  inline_pre_gate: "生成内联修订",
  general: "通用",
  commercial_web: "商业网文",
  literary: "文学向",
  mystery: "悬疑推理",
  emotional: "情感向",
  light_comedy: "轻喜剧",
  experimental: "实验文本",
  summary_ending_overuse: "总结式结尾偏多",
  explanatory_narration_overuse: "解释性叙述偏多",
  voice_merge_trend: "角色声纹趋同",
  rhythm_uniformity_trend: "节奏过于均匀",
  concept_overload_trend: "概念投放过载",
  dialogue_dump_trend: "对白信息倾倒",
  template_phrase: "模板化表达",
  format_artifact: "格式化痕迹",
  dialogue_tag: "对白标签单一",
  emotion_label: "情绪直接标注",
  technical_register: "技术性叙述",
  explanatory_narration: "解释性叙述",
  formulaic_transition: "公式化转折",
  rhythm_uniformity: "节奏过于均匀",
  concept_budget_exceeded: "概念投放超预算",
  unplanned_new_concept: "计划外新概念",
  forbidden_future_concept: "提前揭示未来概念",
  avoided_words: "角色使用回避词",
  voice_merge: "角色声纹趋同",
  dialogue_info_dump: "对白信息倾倒",
  ai_character_voice_merge: "角色声纹趋同",
  character_voice_avoided_word: "角色使用回避词",
  character_dialogue_info_dump: "对白信息倾倒",
  reader_confusion: "读者困惑",
  reader_boredom: "读者无聊",
  reader_inconsistency: "读者感知矛盾",
  reader_cognitive_load: "读者认知负担偏高",
  reader_experience_advice: "读者体验建议",
  low_reading_drive: "阅读驱动力不足",
  low_scene_pressure: "场景压力不足",
  passive_protagonist: "主角能动性不足",
  exposition_driven_reveal: "解释性揭示偏多",
  missing_dialogue_pressure: "对白压力不足",
  weak_hook_out: "出场钩子偏弱",
  mode_mismatch: "写作模式适配不足",
  specificity_budget_unmet: "具体性预算未达成",
  abstraction_over_budget: "抽象表达超预算",
  emotional_claim_without_scene_evidence: "情绪判断缺少场景证据",
  prose_identity_weak: "文体辨识度偏弱",
  over_literary_for_mode: "相对当前模式过度文学化",
  too_plain_for_literary_mode: "文学向模式下语言过平",
  fact_boundary_conflict: "事实边界冲突",
  knowledge_boundary_violation: "人物知识越界",
  plausibility_break: "行为 / 常识不可信",
  memory_plausibility_break: "记忆可信度不足",
  narration_explanation_artifact: "叙事解释腔",
  explanatory_punctuation_artifact: "解释性标点痕迹",
  scene_credibility_unavailable: "场景可信度审计不可用",
  character: "角色",
  location: "地点",
  mention: "提及",
  action: "动作",
  dialogue: "对白",
  observation: "观察",
};

export const REPORT_KEY_LABELS: Record<string, string> = {
  ai_flavor: "AI 味检测",
  ai_quality_coordinator: "AI 质量协调",
  concept_budget: "概念预算",
  character_voice: "角色声纹",
  reader_experience: "读者体验",
  narrative_experience: "叙事体验",
  literary_quality: "文学质量",
  commercial_pacing: "商业节奏",
  scene_credibility: "场景可信度",
  mode_fit: "写作模式适配",
  style_experience_conflict: "风格/体验冲突",
  experience_quality: "体验质量",
  ai_quality_inline_revision: "AI 质量内联修订",
  concept_budget_suggestion: "概念预算建议",
  schema_version: "数据版本",
  id: "编号",
  advisory_id: "建议编号",
  status: "状态",
  mode: "模式",
  writing_mode_id: "写作模式",
  active_profile_id: "当前写作模式",
  overall_level: "整体风险等级",
  score: "得分",
  fit_score: "适配分",
  weighted_score: "加权分",
  scores: "评分",
  metrics: "指标",
  summary: "摘要",
  advisories: "改进建议",
  mismatches: "适配偏差",
  metric_scores: "指标得分",
  quality_guidance_patch: "质量约束补丁",
  experience_guidance: "体验指导",
  literary_quality_guidance: "文学质量指导",
  commercial_pacing_guidance: "商业节奏指导",
  scene_credibility_guidance: "场景可信度约束",
  fact_boundary_guidance: "事实边界约束",
  knowledge_boundary_guidance: "人物知识边界约束",
  plausibility_guidance: "行为可信度约束",
  narration_credibility_guidance: "叙事表达可信度约束",
  style_experience_resolution: "风格/体验协商",
  mode_guardrails: "模式护栏",
  revision_hints: "修订建议",
  risk_summary: "风险摘要",
  coordinator_mode: "协调模式",
  eligible_hint_count: "可自动修订建议数",
  applied_patch_count: "已应用补丁数",
  applied_patches: "已应用补丁",
  skipped_patches: "已跳过补丁",
  draft_hash: "初稿哈希",
  final_hash: "最终稿哈希",
  original_hash: "原片段哈希",
  replacement_hash: "替换片段哈希",
  original_length: "原片段长度",
  replacement_length: "替换片段长度",
  anti_ai_guidance: "去 AI 味创作约束",
  character_voice_guidance: "角色声纹约束",
  problem: "问题",
  strategy: "修订策略",
  preserve: "必须保留",
  auto_revise_allowed: "允许自动修订",
  severity_level: "严重程度",
  source_mode: "来源模式",
  source_checker: "来源检查器",
  needs_user_confirm: "需要用户确认",
  violations: "违规项",
  violation_count: "违规项数量",
  text_length: "文本长度",
  template_phrase_hits: "模板短语次数",
  summary_ending_hits: "总结式结尾次数",
  technical_register_hits: "技术语体次数",
  emotion_label_hits: "情绪标签次数",
  dialogue_tag_hits: "对白标签次数",
  explanatory_narration_hits: "解释性叙述次数",
  formulaic_transition_hits: "公式化转折次数",
  sentence_count: "句子数量",
  sentence_length_cv: "句长变化系数",
  paragraph_count: "段落数量",
  paragraph_length_cv: "段长变化系数",
  type: "类型",
  severity: "严重程度",
  detail: "详情",
  target_span: "目标片段",
  expected_behavior: "期望效果",
  detector: "检查器",
  confidence: "置信度",
  candidate_patch: "候选修改",
  reveal_control: "信息揭示控制",
  new_concept_budget: "新概念预算",
  allowed_new_concepts: "允许的新概念",
  deepen_existing_concepts: "可深化概念",
  forbidden_future_concepts: "禁止提前揭示概念",
  preferred_carriers: "推荐承载方式",
  detected_concepts: "检测到的概念",
  dialogue_count: "对白数量",
  speaker_count: "说话角色数量",
  reason: "原因",
  continue_reading: "继续阅读意愿",
  reading_drive: "阅读驱动力",
  clarity: "清晰度",
  cognitive_load: "认知负担",
  emotional_engagement: "情绪投入",
  dramatic_pressure: "戏剧压力",
  protagonist_agency: "主角能动性",
  payoff_potential: "回收潜力",
  pacing: "节奏",
  specificity: "具体性",
  abstraction_control: "抽象控制",
  sensory_precision: "感官精度",
  prose_identity: "文体辨识度",
  rhythm_variation: "节奏变化",
  style_alignment: "风格一致性",
  cultural_texture: "文化质感",
  mode_alignment: "模式一致性",
  confusions: "困惑点",
  drop_points: "可能弃读点",
  degraded: "是否降级",
  error: "错误信息",
  reports: "报告",
  quality_memory: "质量记忆",
  recent_quality_patterns: "近期质量模式",
  mode_fit_history: "模式适配历史",
  count: "次数",
  last_seen_chapter: "最近章节",
  last_seen_scene: "最近场景",
  suggestion: "建议",
  avg_mode_fit: "平均适配分",
  sample_count: "样本数",
  style_conflicts: "风格冲突",
  conflict_type: "冲突类型",
  resolution: "协商结果",
};

export function displayValue(value: string, fallback = "未识别项"): string {
  return DISPLAY_VALUE_LABELS[value] || fallback;
}

export function displayKey(key: string): string {
  return REPORT_KEY_LABELS[key] || HEALTH_SUMMARY_LABELS[key] || "其他项目";
}

export function chapterTitleWithoutNumber(
  chapterNumber: number,
  rawTitle: string | null | undefined,
): string {
  const title = String(rawTitle || "").trim();
  if (!title) return "";
  const matchingPrefix = new RegExp(`^第\\s*${chapterNumber}\\s*章`);
  return title
    .replace(matchingPrefix, "")
    .trim()
    .replace(/^(?:·|・|:|：|-|—)\s*/, "")
    .trim();
}

export function formatChapterLabel(
  chapterNumber: number,
  rawTitle: string | null | undefined,
  fallback = "",
): string {
  const title = chapterTitleWithoutNumber(chapterNumber, rawTitle) || fallback.trim();
  return title ? `第${chapterNumber}章 ${title}` : `第${chapterNumber}章`;
}
